version: '3.8'
services:
  spring:
    build:
      context: ./berezovskoye-backend/
      dockerfile: Dockerfile
    #ports:
    #  - 8080:8080

  nextjs:
    build:
      context: ./berezovskoye-frontend/
      dockerfile: Dockerfile
    #ports:
    #  - 3000:3000
 